### PR TITLE
Minor doc fixes

### PR DESCRIPTION
**Pull request by thomdixon**
I noticed the documentation wasn't displaying correctly in hex (my bad!) so I went ahead and fixed that. I also updated the copyright year, and fixed a small Credo error I noticed while updating the docs.

### CODE REVIEW

**Comment by thomdixon** [comment]
Looks like CI failed to create the Elixir environment? For what it's worth:

```sh
$ mix test                                      
Compiling 2 files (.ex)
.....warning: variable "id" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/service_test.exs:10: ServiceTest."test new/1 returns a service struct"/1

warning: variable "urls" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/service_test.exs:10: ServiceTest."test new/1 returns a service struct"/1

...........warning: unused alias Service
  test/yubikey_otp_test.exs:7

............................

Finished in 1.0 seconds
23 doctests, 21 tests, 0 failures

Randomized with seed 102593

```

**Comment by binaryape** [comment]
Thanks! I'll get this sorted out

**Comment by binaryape** [comment]
"OpenSSL might not be installed on this system." Well it was before, Github.

**Comment by thomdixon** [comment]
Looks like `actions/setup-elixir` is deprecated and they suggest using `erlef/setup-beam` instead:

* https://github.com/actions/setup-elixir#setup-elixir
* https://github.com/erlef/setup-beam

**Comment by thomdixon** [comment]
I opened #4 to fix this issue. Once that gets merged, I'll rebase master and kick this PR again. :+1:

**Comment by binaryape** [comment]
I've updated the Github Actions now (thanks for that!)

**Comment by thomdixon** [comment]
Woot! :champagne:

**Comment by binaryape** [comment]
Cheers! I'll do a new release ASAP

**Pull request merged**
